/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as BusinessLogicRouteImport } from './routes/business-logic'
import { Route as DatabaseRouteImport } from './routes/database'
import { Route as HealthRouteImport } from './routes/health'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as ApiAssessmentsRouteImport } from './routes/api/assessments'
import { Route as ApiDashboardRouteImport } from './routes/api/dashboard'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiSimulationRouteImport } from './routes/api/simulation'
import { Route as ApiAssessmentsAssessmentIdRouteImport } from './routes/api/assessments.$assessmentId'
import { Route as ApiCreditScoresAssessmentIdRouteImport } from './routes/api/credit-scores.$assessmentId'
import { Route as ApiObservabilityLogsRouteImport } from './routes/api/observability.logs'
import { Route as ApiV1AssessmentsRouteImport } from './routes/api/v1.assessments'
import { Route as ApiV1DashboardRouteImport } from './routes/api/v1.dashboard'
import { Route as ApiV1HealthRouteImport } from './routes/api/v1.health'
import { Route as ApiV1SimulationRouteImport } from './routes/api/v1.simulation'
import { Route as ApiAssessmentsAssessmentIdStatusRouteImport } from './routes/api/assessments.$assessmentId.status'
import { Route as ApiV1AssessmentsAssessmentIdRouteImport } from './routes/api/v1.assessments.$assessmentId'
import { Route as ApiV1CreditScoresAssessmentIdRouteImport } from './routes/api/v1.credit-scores.$assessmentId'
import { Route as ApiV1ObservabilityLogsRouteImport } from './routes/api/v1.observability.logs'
import { Route as ApiV1AssessmentsAssessmentIdStatusRouteImport } from './routes/api/v1.assessments.$assessmentId.status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessLogicRoute = BusinessLogicRouteImport.update({
  id: '/business-logic',
  path: '/business-logic',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabaseRoute = DatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssessmentsRoute = ApiAssessmentsRouteImport.update({
  id: '/api/assessments',
  path: '/api/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardRoute = ApiDashboardRouteImport.update({
  id: '/api/dashboard',
  path: '/api/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSimulationRoute = ApiSimulationRouteImport.update({
  id: '/api/simulation',
  path: '/api/simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssessmentsAssessmentIdRoute =
  ApiAssessmentsAssessmentIdRouteImport.update({
    id: '/$assessmentId',
    path: '/$assessmentId',
    getParentRoute: () => ApiAssessmentsRoute,
  } as any)
const ApiCreditScoresAssessmentIdRoute =
  ApiCreditScoresAssessmentIdRouteImport.update({
    id: '/api/credit-scores/$assessmentId',
    path: '/api/credit-scores/$assessmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiObservabilityLogsRoute = ApiObservabilityLogsRouteImport.update({
  id: '/api/observability/logs',
  path: '/api/observability/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AssessmentsRoute = ApiV1AssessmentsRouteImport.update({
  id: '/api/v1/assessments',
  path: '/api/v1/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DashboardRoute = ApiV1DashboardRouteImport.update({
  id: '/api/v1/dashboard',
  path: '/api/v1/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1HealthRoute = ApiV1HealthRouteImport.update({
  id: '/api/v1/health',
  path: '/api/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SimulationRoute = ApiV1SimulationRouteImport.update({
  id: '/api/v1/simulation',
  path: '/api/v1/simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssessmentsAssessmentIdStatusRoute =
  ApiAssessmentsAssessmentIdStatusRouteImport.update({
    id: '/status',
    path: '/status',
    getParentRoute: () => ApiAssessmentsAssessmentIdRoute,
  } as any)
const ApiV1AssessmentsAssessmentIdRoute =
  ApiV1AssessmentsAssessmentIdRouteImport.update({
    id: '/$assessmentId',
    path: '/$assessmentId',
    getParentRoute: () => ApiV1AssessmentsRoute,
  } as any)
const ApiV1CreditScoresAssessmentIdRoute =
  ApiV1CreditScoresAssessmentIdRouteImport.update({
    id: '/api/v1/credit-scores/$assessmentId',
    path: '/api/v1/credit-scores/$assessmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ObservabilityLogsRoute = ApiV1ObservabilityLogsRouteImport.update({
  id: '/api/v1/observability/logs',
  path: '/api/v1/observability/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AssessmentsAssessmentIdStatusRoute =
  ApiV1AssessmentsAssessmentIdStatusRouteImport.update({
    id: '/status',
    path: '/status',
    getParentRoute: () => ApiV1AssessmentsAssessmentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-docs': typeof ApiDocsRoute
  '/architecture': typeof ArchitectureRoute
  '/assessment': typeof AssessmentRoute
  '/business-logic': typeof BusinessLogicRoute
  '/database': typeof DatabaseRoute
  '/health': typeof HealthRoute
  '/logs': typeof LogsRoute
  '/roadmap': typeof RoadmapRoute
  '/security': typeof SecurityRoute
  '/api/$': typeof ApiSplatRoute
  '/api/assessments': typeof ApiAssessmentsRouteWithChildren
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/api/simulation': typeof ApiSimulationRoute
  '/api/assessments/$assessmentId': typeof ApiAssessmentsAssessmentIdRouteWithChildren
  '/api/credit-scores/$assessmentId': typeof ApiCreditScoresAssessmentIdRoute
  '/api/observability/logs': typeof ApiObservabilityLogsRoute
  '/api/v1/assessments': typeof ApiV1AssessmentsRouteWithChildren
  '/api/v1/dashboard': typeof ApiV1DashboardRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/simulation': typeof ApiV1SimulationRoute
  '/api/assessments/$assessmentId/status': typeof ApiAssessmentsAssessmentIdStatusRoute
  '/api/v1/assessments/$assessmentId': typeof ApiV1AssessmentsAssessmentIdRouteWithChildren
  '/api/v1/credit-scores/$assessmentId': typeof ApiV1CreditScoresAssessmentIdRoute
  '/api/v1/observability/logs': typeof ApiV1ObservabilityLogsRoute
  '/api/v1/assessments/$assessmentId/status': typeof ApiV1AssessmentsAssessmentIdStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-docs': typeof ApiDocsRoute
  '/architecture': typeof ArchitectureRoute
  '/assessment': typeof AssessmentRoute
  '/business-logic': typeof BusinessLogicRoute
  '/database': typeof DatabaseRoute
  '/health': typeof HealthRoute
  '/logs': typeof LogsRoute
  '/roadmap': typeof RoadmapRoute
  '/security': typeof SecurityRoute
  '/api/$': typeof ApiSplatRoute
  '/api/assessments': typeof ApiAssessmentsRouteWithChildren
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/api/simulation': typeof ApiSimulationRoute
  '/api/assessments/$assessmentId': typeof ApiAssessmentsAssessmentIdRouteWithChildren
  '/api/credit-scores/$assessmentId': typeof ApiCreditScoresAssessmentIdRoute
  '/api/observability/logs': typeof ApiObservabilityLogsRoute
  '/api/v1/assessments': typeof ApiV1AssessmentsRouteWithChildren
  '/api/v1/dashboard': typeof ApiV1DashboardRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/simulation': typeof ApiV1SimulationRoute
  '/api/assessments/$assessmentId/status': typeof ApiAssessmentsAssessmentIdStatusRoute
  '/api/v1/assessments/$assessmentId': typeof ApiV1AssessmentsAssessmentIdRouteWithChildren
  '/api/v1/credit-scores/$assessmentId': typeof ApiV1CreditScoresAssessmentIdRoute
  '/api/v1/observability/logs': typeof ApiV1ObservabilityLogsRoute
  '/api/v1/assessments/$assessmentId/status': typeof ApiV1AssessmentsAssessmentIdStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-docs': typeof ApiDocsRoute
  '/architecture': typeof ArchitectureRoute
  '/assessment': typeof AssessmentRoute
  '/business-logic': typeof BusinessLogicRoute
  '/database': typeof DatabaseRoute
  '/health': typeof HealthRoute
  '/logs': typeof LogsRoute
  '/roadmap': typeof RoadmapRoute
  '/security': typeof SecurityRoute
  '/api/$': typeof ApiSplatRoute
  '/api/assessments': typeof ApiAssessmentsRouteWithChildren
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/api/simulation': typeof ApiSimulationRoute
  '/api/assessments/$assessmentId': typeof ApiAssessmentsAssessmentIdRouteWithChildren
  '/api/credit-scores/$assessmentId': typeof ApiCreditScoresAssessmentIdRoute
  '/api/observability/logs': typeof ApiObservabilityLogsRoute
  '/api/v1/assessments': typeof ApiV1AssessmentsRouteWithChildren
  '/api/v1/dashboard': typeof ApiV1DashboardRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/simulation': typeof ApiV1SimulationRoute
  '/api/assessments/$assessmentId/status': typeof ApiAssessmentsAssessmentIdStatusRoute
  '/api/v1/assessments/$assessmentId': typeof ApiV1AssessmentsAssessmentIdRouteWithChildren
  '/api/v1/credit-scores/$assessmentId': typeof ApiV1CreditScoresAssessmentIdRoute
  '/api/v1/observability/logs': typeof ApiV1ObservabilityLogsRoute
  '/api/v1/assessments/$assessmentId/status': typeof ApiV1AssessmentsAssessmentIdStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/api-docs'
    | '/architecture'
    | '/assessment'
    | '/business-logic'
    | '/database'
    | '/health'
    | '/logs'
    | '/roadmap'
    | '/security'
    | '/api/$'
    | '/api/assessments'
    | '/api/dashboard'
    | '/api/health'
    | '/api/simulation'
    | '/api/assessments/$assessmentId'
    | '/api/credit-scores/$assessmentId'
    | '/api/observability/logs'
    | '/api/v1/assessments'
    | '/api/v1/dashboard'
    | '/api/v1/health'
    | '/api/v1/simulation'
    | '/api/assessments/$assessmentId/status'
    | '/api/v1/assessments/$assessmentId'
    | '/api/v1/credit-scores/$assessmentId'
    | '/api/v1/observability/logs'
    | '/api/v1/assessments/$assessmentId/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/api-docs'
    | '/architecture'
    | '/assessment'
    | '/business-logic'
    | '/database'
    | '/health'
    | '/logs'
    | '/roadmap'
    | '/security'
    | '/api/$'
    | '/api/assessments'
    | '/api/dashboard'
    | '/api/health'
    | '/api/simulation'
    | '/api/assessments/$assessmentId'
    | '/api/credit-scores/$assessmentId'
    | '/api/observability/logs'
    | '/api/v1/assessments'
    | '/api/v1/dashboard'
    | '/api/v1/health'
    | '/api/v1/simulation'
    | '/api/assessments/$assessmentId/status'
    | '/api/v1/assessments/$assessmentId'
    | '/api/v1/credit-scores/$assessmentId'
    | '/api/v1/observability/logs'
    | '/api/v1/assessments/$assessmentId/status'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/api-docs'
    | '/architecture'
    | '/assessment'
    | '/business-logic'
    | '/database'
    | '/health'
    | '/logs'
    | '/roadmap'
    | '/security'
    | '/api/$'
    | '/api/assessments'
    | '/api/dashboard'
    | '/api/health'
    | '/api/simulation'
    | '/api/assessments/$assessmentId'
    | '/api/credit-scores/$assessmentId'
    | '/api/observability/logs'
    | '/api/v1/assessments'
    | '/api/v1/dashboard'
    | '/api/v1/health'
    | '/api/v1/simulation'
    | '/api/assessments/$assessmentId/status'
    | '/api/v1/assessments/$assessmentId'
    | '/api/v1/credit-scores/$assessmentId'
    | '/api/v1/observability/logs'
    | '/api/v1/assessments/$assessmentId/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApiDocsRoute: typeof ApiDocsRoute
  ArchitectureRoute: typeof ArchitectureRoute
  AssessmentRoute: typeof AssessmentRoute
  BusinessLogicRoute: typeof BusinessLogicRoute
  DatabaseRoute: typeof DatabaseRoute
  HealthRoute: typeof HealthRoute
  LogsRoute: typeof LogsRoute
  RoadmapRoute: typeof RoadmapRoute
  SecurityRoute: typeof SecurityRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiAssessmentsRoute: typeof ApiAssessmentsRouteWithChildren
  ApiDashboardRoute: typeof ApiDashboardRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiSimulationRoute: typeof ApiSimulationRoute
  ApiCreditScoresAssessmentIdRoute: typeof ApiCreditScoresAssessmentIdRoute
  ApiObservabilityLogsRoute: typeof ApiObservabilityLogsRoute
  ApiV1AssessmentsRoute: typeof ApiV1AssessmentsRouteWithChildren
  ApiV1DashboardRoute: typeof ApiV1DashboardRoute
  ApiV1HealthRoute: typeof ApiV1HealthRoute
  ApiV1SimulationRoute: typeof ApiV1SimulationRoute
  ApiV1CreditScoresAssessmentIdRoute: typeof ApiV1CreditScoresAssessmentIdRoute
  ApiV1ObservabilityLogsRoute: typeof ApiV1ObservabilityLogsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-logic': {
      id: '/business-logic'
      path: '/business-logic'
      fullPath: '/business-logic'
      preLoaderRoute: typeof BusinessLogicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/database': {
      id: '/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof DatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assessments': {
      id: '/api/assessments'
      path: '/api/assessments'
      fullPath: '/api/assessments'
      preLoaderRoute: typeof ApiAssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard': {
      id: '/api/dashboard'
      path: '/api/dashboard'
      fullPath: '/api/dashboard'
      preLoaderRoute: typeof ApiDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/simulation': {
      id: '/api/simulation'
      path: '/api/simulation'
      fullPath: '/api/simulation'
      preLoaderRoute: typeof ApiSimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assessments/$assessmentId': {
      id: '/api/assessments/$assessmentId'
      path: '/$assessmentId'
      fullPath: '/api/assessments/$assessmentId'
      preLoaderRoute: typeof ApiAssessmentsAssessmentIdRouteImport
      parentRoute: typeof ApiAssessmentsRoute
    }
    '/api/credit-scores/$assessmentId': {
      id: '/api/credit-scores/$assessmentId'
      path: '/api/credit-scores/$assessmentId'
      fullPath: '/api/credit-scores/$assessmentId'
      preLoaderRoute: typeof ApiCreditScoresAssessmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/observability/logs': {
      id: '/api/observability/logs'
      path: '/api/observability/logs'
      fullPath: '/api/observability/logs'
      preLoaderRoute: typeof ApiObservabilityLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/assessments': {
      id: '/api/v1/assessments'
      path: '/api/v1/assessments'
      fullPath: '/api/v1/assessments'
      preLoaderRoute: typeof ApiV1AssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/dashboard': {
      id: '/api/v1/dashboard'
      path: '/api/v1/dashboard'
      fullPath: '/api/v1/dashboard'
      preLoaderRoute: typeof ApiV1DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/health': {
      id: '/api/v1/health'
      path: '/api/v1/health'
      fullPath: '/api/v1/health'
      preLoaderRoute: typeof ApiV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/simulation': {
      id: '/api/v1/simulation'
      path: '/api/v1/simulation'
      fullPath: '/api/v1/simulation'
      preLoaderRoute: typeof ApiV1SimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assessments/$assessmentId/status': {
      id: '/api/assessments/$assessmentId/status'
      path: '/status'
      fullPath: '/api/assessments/$assessmentId/status'
      preLoaderRoute: typeof ApiAssessmentsAssessmentIdStatusRouteImport
      parentRoute: typeof ApiAssessmentsAssessmentIdRoute
    }
    '/api/v1/assessments/$assessmentId': {
      id: '/api/v1/assessments/$assessmentId'
      path: '/$assessmentId'
      fullPath: '/api/v1/assessments/$assessmentId'
      preLoaderRoute: typeof ApiV1AssessmentsAssessmentIdRouteImport
      parentRoute: typeof ApiV1AssessmentsRoute
    }
    '/api/v1/credit-scores/$assessmentId': {
      id: '/api/v1/credit-scores/$assessmentId'
      path: '/api/v1/credit-scores/$assessmentId'
      fullPath: '/api/v1/credit-scores/$assessmentId'
      preLoaderRoute: typeof ApiV1CreditScoresAssessmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/observability/logs': {
      id: '/api/v1/observability/logs'
      path: '/api/v1/observability/logs'
      fullPath: '/api/v1/observability/logs'
      preLoaderRoute: typeof ApiV1ObservabilityLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/assessments/$assessmentId/status': {
      id: '/api/v1/assessments/$assessmentId/status'
      path: '/status'
      fullPath: '/api/v1/assessments/$assessmentId/status'
      preLoaderRoute: typeof ApiV1AssessmentsAssessmentIdStatusRouteImport
      parentRoute: typeof ApiV1AssessmentsAssessmentIdRoute
    }
  }
}

interface ApiAssessmentsAssessmentIdRouteChildren {
  ApiAssessmentsAssessmentIdStatusRoute: typeof ApiAssessmentsAssessmentIdStatusRoute
}

const ApiAssessmentsAssessmentIdRouteChildren: ApiAssessmentsAssessmentIdRouteChildren =
  {
    ApiAssessmentsAssessmentIdStatusRoute:
      ApiAssessmentsAssessmentIdStatusRoute,
  }

const ApiAssessmentsAssessmentIdRouteWithChildren =
  ApiAssessmentsAssessmentIdRoute._addFileChildren(
    ApiAssessmentsAssessmentIdRouteChildren,
  )

interface ApiAssessmentsRouteChildren {
  ApiAssessmentsAssessmentIdRoute: typeof ApiAssessmentsAssessmentIdRouteWithChildren
}

const ApiAssessmentsRouteChildren: ApiAssessmentsRouteChildren = {
  ApiAssessmentsAssessmentIdRoute: ApiAssessmentsAssessmentIdRouteWithChildren,
}

const ApiAssessmentsRouteWithChildren = ApiAssessmentsRoute._addFileChildren(
  ApiAssessmentsRouteChildren,
)

interface ApiV1AssessmentsAssessmentIdRouteChildren {
  ApiV1AssessmentsAssessmentIdStatusRoute: typeof ApiV1AssessmentsAssessmentIdStatusRoute
}

const ApiV1AssessmentsAssessmentIdRouteChildren: ApiV1AssessmentsAssessmentIdRouteChildren =
  {
    ApiV1AssessmentsAssessmentIdStatusRoute:
      ApiV1AssessmentsAssessmentIdStatusRoute,
  }

const ApiV1AssessmentsAssessmentIdRouteWithChildren =
  ApiV1AssessmentsAssessmentIdRoute._addFileChildren(
    ApiV1AssessmentsAssessmentIdRouteChildren,
  )

interface ApiV1AssessmentsRouteChildren {
  ApiV1AssessmentsAssessmentIdRoute: typeof ApiV1AssessmentsAssessmentIdRouteWithChildren
}

const ApiV1AssessmentsRouteChildren: ApiV1AssessmentsRouteChildren = {
  ApiV1AssessmentsAssessmentIdRoute:
    ApiV1AssessmentsAssessmentIdRouteWithChildren,
}

const ApiV1AssessmentsRouteWithChildren =
  ApiV1AssessmentsRoute._addFileChildren(ApiV1AssessmentsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApiDocsRoute: ApiDocsRoute,
  ArchitectureRoute: ArchitectureRoute,
  AssessmentRoute: AssessmentRoute,
  BusinessLogicRoute: BusinessLogicRoute,
  DatabaseRoute: DatabaseRoute,
  HealthRoute: HealthRoute,
  LogsRoute: LogsRoute,
  RoadmapRoute: RoadmapRoute,
  SecurityRoute: SecurityRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiAssessmentsRoute: ApiAssessmentsRouteWithChildren,
  ApiDashboardRoute: ApiDashboardRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiSimulationRoute: ApiSimulationRoute,
  ApiCreditScoresAssessmentIdRoute: ApiCreditScoresAssessmentIdRoute,
  ApiObservabilityLogsRoute: ApiObservabilityLogsRoute,
  ApiV1AssessmentsRoute: ApiV1AssessmentsRouteWithChildren,
  ApiV1DashboardRoute: ApiV1DashboardRoute,
  ApiV1HealthRoute: ApiV1HealthRoute,
  ApiV1SimulationRoute: ApiV1SimulationRoute,
  ApiV1CreditScoresAssessmentIdRoute: ApiV1CreditScoresAssessmentIdRoute,
  ApiV1ObservabilityLogsRoute: ApiV1ObservabilityLogsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
